@PORT = 3000
@api = http://localhost:3000/
@api.login = http://localhost:3000/login
@api.register = http://localhost:3000/register
@api.verify = http://localhost:3000/verify
@api.logout = http://localhost:3000/logout

###

GET {{api}}/verify

###

POST {{api}}/logout

###

POST {{api.login}}
Content-Type: application/json

{
  "username": "test13",
  "password": "testpass123"
}

###

GET {{api.verify}}

###

POST {{api.register}}
Content-Type: application/json

{
  "username": "test13",
  "email" : "test13@gmail.com",
  "password": "testpass123"
}






