@api = http://localhost:3001/tasks
@api.register = http://localhost:3000/register
@api.login = http://localhost:3000/login
@api.profile = http://localhost:3000/profile

GET {{api}}/111

###

###

GET {{api.register}}

###

POST {{api.register}}
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@gmail.com",
  "password_hash": "test2"
}

###

POST {{api.login}}
Content-Type: application/json

{
  "username": "test2",
  "password": "test2"
}

###

#curl -X GET http://localhost:3000/profile
#-H 'Authorization: Bearer <tu_token_aqui>'
GET http://localhost:3000/profile
Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjYxMjk5MTksImV4cCI6MTcyNjIxNjMxOX0.E-KXyNrllU4t6un4U-fCZyHfgcTy6XghA5jpy0Nmw-0>








